kernel:
  image: linuxkit/kernel:5.10.34
  cmdline: "console=ttyS0"

init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a

onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8

services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true

  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /usr/share/nginx/html/index.html:/usr/share/nginx/html/index.html

files:
  - path: /usr/share/nginx/html/index.html
    source: index.html
    mode: "0744"
    optional: false

trust:
  org:
    - linuxkit
